apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: default
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-sso@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.k-space.ee
spec:
  rules:
  - host: playground.k-space.ee
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: log-viewer-frontend
            port:
              number: 8080
  tls:
  - hosts:
    - playground.k-space.ee
    secretName: playground-tls
---
apiVersion: v1
kind: Service
metadata:
  name: log-viewer-frontend
spec:
  type: ClusterIP
  selector:
    app: log-viewer-frontend
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-viewer-frontend
spec:
  selector:
    matchLabels:
      app: log-viewer-frontend
  template:
    metadata:
      labels:
        app: log-viewer-frontend
    spec:
      containers:
      - name: log-viewer-frontend
        image: harbor.k-space.ee/playground/log-viewer-frontend
        ports:
        - containerPort: 8080
